create table course (
    id bigint generated by default as identity,
    title varchar(255) not null,
    creator_id bigint not null,
    created_at timestamp not null,
    updated_at timestamp,
    primary key (id)
);

create table session (
    id bigint generated by default as identity,
    course_id bigint not null,
    session_type varchar(20) not null,
    status varchar(20) not null,
    start_date date not null,
    end_date date not null,
    max_enrollment int,
    price int,
    created_at timestamp not null,
    updated_at timestamp,
    primary key (id),
    foreign key (course_id) references course(id)
);

create table cover_image (
    id bigint generated by default as identity,
    session_id bigint not null,
    filename varchar(255) not null,
    file_size bigint not null,
    width int not null,
    height int not null,
    image_type varchar(20) not null,
    primary key (id),
    foreign key (session_id) references session(id)
);

create table enrollment (
    id bigint generated by default as identity,
    session_id bigint not null,
    student_id bigint not null,
    created_at timestamp not null,
    primary key (id),
    foreign key (session_id) references session(id),
    unique (session_id, student_id)
);

create table ns_user (
    id bigint generated by default as identity,
    user_id varchar(20) not null,
    password varchar(20) not null,
    name varchar(20) not null,
    email varchar(50),
    created_at timestamp not null,
    updated_at timestamp,
    primary key (id)
);

create table question (
    id bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp,
    contents clob,
    deleted boolean not null,
    title varchar(100) not null,
    writer_id bigint,
    primary key (id)
);

create table answer (
    id bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp,
    contents clob,
    deleted boolean not null,
    question_id bigint,
    writer_id bigint,
    primary key (id)
);

create table delete_history (
    id bigint not null,
    content_id bigint,
    content_type varchar(255),
    created_date timestamp,
    deleted_by_id bigint,
    primary key (id)
);
